# This file was generated by GoReleaser. DO NOT EDIT.
class Octo < Formula
  desc "cli client for GitHub"
  homepage "https://github.com/octo-cli/octo-cli"
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/octo-cli/octo-cli/releases/download/v0.5.1/octo-cli_0.5.1_Darwin_x86_64.tar.gz"
    sha256 "21498d93cb8ba61fc684c7e5566a2925dbe9909ccbc6290bfbee25486f3ef31f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/octo-cli/octo-cli/releases/download/v0.5.1/octo-cli_0.5.1_Linux_x86_64.tar.gz"
      sha256 "b11b10e50c639c8641c575b89cc6b00b631f3c2cdc8a2effc098992a6075902e"
    end
  end

  def install
    bin.install "octo"
  end
end
